services:
  - type: web
    name: my-service
    env: node
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg
      apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk1.0-0 libcups2 libdbus-1-3 libxcomposite1 libxrandr2 libxdamage1 libgbm1 libpango1.0-0 libnss3 lsb-release xdg-utils
      npm install
    startCommand: npm start
envVars:
  - key: CHROME_BIN
    value: /opt/render/project/.render/chrome-linux/chrome
